PREDEFINED_COMMANDS = [
    "follow me",
    "follow the yellow bin",
    "stop",
    "stop navigation",
    "pause",
    "resume",
    "start exploring",
    "stop exploring",
    "here is the bin",
    "here is the green bin",
    "look at the green bin",
    "go to lab",
    "go to entrance",
    "go to kitchen",
    "go to the red bin",
    "go to the green bin",
    "go to the blue bin",
    "go to the yellow bin",
    "navigate to bin 1",
    "navigate to bin 2",
    "start tour",
]
